### ISSUE TITLE
what required?

### ISSUE THREAD

**Issue by uga-rosa** [kdheepak/cmp-latex-symbols#1]
Error detected while processing TextChangedI Autocommands for "*":
E5108: Error executing lua ...s/start/cmp-latex-symbols/lua/cmp_latex_symbols/init.lua:1619: attempt to call global 'dump' (a nil value)

**Comment by kdheepak** [comment]
My bad. Fixed in https://github.com/kdheepak/cmp-latex-symbols/commit/07412e1fd757eee19840091c635b81f04edca3c9.
