### ISSUE TITLE
some names are inconsistent with REPL and julia-vim

### ISSUE THREAD

**Issue by ExpandingMan** [kdheepak/cmp-latex-symbols#5]
There are some values that seem to be named differently than than both the Julia REPL and `julia-vim`.

In particular, I'm referring to letters like `\scrA` which in this package is called `\mbfscrA`.  I don't see what generates the list here, so I'm not sure what's causing this.

If you don't have a generator, I can help: we can adapt [this](https://gitlab.com/ExpandingMan/compe-latex) (my plugin was a little screwed up but I'm pretty sure I generated the symbols correctly).

**Comment by kdheepak** [comment]
I’m happy to accept a PR that fixes or adds more symbols. I took the existing list from `compe-latex-symbols` repo and pasted it in this repo. I did find a more comprehensive list somewhere else (I’m on my mobile now) and meant to cross check with this one, so I’m glad you opened this issue.

**Comment by ExpandingMan** [comment]
No worries, I'll do it.  I just want to confirm though, you are good with using the list in the `julia` repo as the canonical list right?

**Comment by kdheepak** [comment]
I think we can have a superset of all the lists, right? That way users can complete their preferred way.

**Comment by ExpandingMan** [comment]
What other lists are you referring to?  It would of course depend on whether there are conflicts.

**Comment by kdheepak** [comment]
Let me share the list I found when I’m back at my computer. If there are conflicts in the values of the table it wouldn’t matter. I don’t expect there’ll be conflicts in the keys.

**Comment by ExpandingMan** [comment]
Alright, I wound up just duplicating this, see [here](https://gitlab.com/ExpandingMan/cmp-latex).  You can see in `generate_items.jl` that this necessarily uses all and only the latex and emoji symbols defined by the Julia REPL.  I think I'll just keep that package that way, and then you can use it to merge with whatever lists you'd like and put it in this package, that way there'll be an option (presumably these won't need much updating).

**Comment by kdheepak** [comment]
Thanks for sharing. This is the link that I was talking about: <http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt>. I'll combine this and your `generate_items.jl` and report back here.

**Comment by kdheepak** [comment]
I generated a new list: <https://github.com/kdheepak/cmp-latex-symbols/blob/49406012d77e7f13dc04d8d5cd24c60cfd0f468c/lua/cmp_latex_symbols/items.lua>

This is based on your `generate_items.jl` but uses <http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt> as the source. In addition to that link, it also adds all the Julia symbols (if they didn't already exist). You can find the script here: <https://github.com/kdheepak/cmp-latex-symbols/blob/49406012d77e7f13dc04d8d5cd24c60cfd0f468c/scripts/generate.jl>

For example, in your source, `\AC` will not autocomplete to anything but `\sinewave` will. `unimathsymbols` defines both alternating current and sinewave as the same symbol:

```
0223F^∿^\AC^\sinewave^N^mathord^wasysym^SINE WAVE, alternating current
```

Also, there's symbols like this one:

```
0221B^∛^\sqrt[3]^\cuberoot^L^mathradical^^CUBE ROOT
```

which are not defined in Julia's REPL afaict. That works with this source.

`unimathsymbols.txt` also defines alias commands and compatible mappings, which have all been added to this source. With almost 5000 entries, this list should be comprehensive.

Lastly, I like using colon to trigger emoji completion and backslash to trigger LaTeX completion, so I removed the Julia emoji completion from your script. I use [a separate source](https://github.com/hrsh7th/cmp-emoji) for emoji completion.

I've updated the README and linked to your repo in case anyone is interested in a Julia only completion source.
